### ISSUE TITLE
no function error

### ISSUE THREAD

**Issue by sujansujan** [schwifty42069/piptv#11] opened 2019-09-20 16:35 UTC
i have been getting this every time after choosing the channel
i am using ubuntu 19. i just followed everything that provided here. sorry i am noob to this

trying to tune to tv land...

Traceback (most recent call last):

File "piptv.py", line 167, in <module>

main()

File "piptv.py", line 163, in main

stb.tune_to_channel(command)

File "piptv.py", line 118, in tune_to_channel

self.player.set_mrl(hotlink)

File "/home/sujan/.local/lib/python3.7/site-packages/vlc.py", line 3331, in set_mrl

m = self.get_instance().media_new(mrl, *options)

File "/home/sujan/.local/lib/python3.7/site-packages/vlc.py", line 1908, in media_new

if ':' in mrl and mrl.index(':') > 1:

TypeError: argument of type 'NoneType' is not iterable

**Comment by schwifty42069** [comment] 2019-09-20 17:04
When did you download the version of piptv you're trying to use? Also, do you have VLC installed on your system? If not, open a terminal and type:

apt install vlc 

and then try again

**Comment by sujansujan** [comment] 2019-09-20 17:08
downloaded it about 10 hrs ago. i even installed vlc from terminal.

**Comment by schwifty42069** [comment] 2019-09-20 17:11
Hm okay. Is it just tv land? Or any channel? Cause I can tune to tv land no problem too, and I am on Ubuntu 19.

**Comment by sujansujan** [comment] 2019-09-20 17:12
every channel i tried gave the same result.

**Comment by schwifty42069** [comment] 2019-09-20 17:15
Okay, open a python3 shell by typing python3 in a terminal.

type the following:

import requests
from bs4 import BeautifulSoup as Soup

bsoup = Soup(requests.get("http://ustvgo.tv/nfl-network-live-free").text, 'html.parser')

print(bsoup)

Show me what that outputs, just curious if you're getting data back from the request.

**Comment by schwifty42069** [comment] 2019-09-20 17:27
did you get any error when doing pip install from the requirements.txt?

**Comment by schwifty42069** [comment] 2019-09-20 18:24
Closing this for now, as I can't reproduce your issue in Ubuntu 19. If you continue to have problems, open a new issue.

**Closed by schwifty42069** 2019-09-20 18:24 UTC
